# -*- coding: utf-8 -*-
"""High Fidelity OpenRouter Loop

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1d7Y5b94_juO-L-UCLva1vgq3q3RhVgeo
"""

import os
import time
import json
import sys

# Try to import OpenAI, warn if missing
try:
    from openai import OpenAI, APIConnectionError, RateLimitError
except ImportError:
    print("CRITICAL: 'openai' library not found. Install via: pip install openai")
    sys.exit(1)

# ==========================================
# CONFIGURATION & CONSTANTS
# ==========================================
# Load from environment for security, or fallback to empty string for testing
API_KEY = os.getenv("OPENROUTER_API_KEY", "")

# Target Model: Using the user-specified Gemini 3 Flash Preview
PRIMARY_MODEL = "google/gemini-3-flash-preview"

# Fallback Models: High-intelligence alternatives if the primary is offline
FALLBACK_MODELS = [
    "google/gemini-2.0-flash-exp",
    "anthropic/claude-3.5-sonnet",
    "meta-llama/llama-3.3-70b-instruct"
]

# Client Initialization without tracking headers
client = OpenAI(
    base_url="https://openrouter.ai/api/v1",
    api_key=API_KEY
)

def extract_provider_metadata(completion_object):
    """
    Safely extracts non-standard OpenRouter metadata (like 'provider')
    from the Pydantic response model.
    """
    try:
        # Pydantic v2 dump to dict to access extra fields
        response_dict = completion_object.model_dump()

        # OpenRouter often injects provider info in the usage or explicit 'provider' field
        # Note: The specific location can vary by SDK version, checking common spots.
        if 'provider' in response_dict:
            return response_dict['provider']

        # Sometimes hidden in 'model' response (e.g. "openai/gpt-4o")
        return response_dict.get('model', 'unknown-model')
    except Exception:
        # Fallback for older SDKs
        return getattr(completion_object, 'model', 'unknown')

def execute_high_fidelity_call(prompt_text, sample_id="TEST"):
    """
    Performs a maximize-performance inference call.
    """
    print(f"\n[{sample_id}] Initiating Request...")
    print(f"[{sample_id}] Constraints: fp16/bf16 | Provider: Auto-routed (Quality First)")

    try:
        start_time = time.time()

        completion = client.chat.completions.create(
            model=PRIMARY_MODEL,
            messages=[
                {
                    "role": "system",
                    "content": (
                        "ROLE: Deterministic Computational Engine. "
                        "OBJECTIVE: Provide accurate, unquantized logic. "
                        "OUTPUT: JSON format only."
                    )
                },
                {"role": "user", "content": prompt_text}
            ],

            # --- DETERMINISTIC SAMPLING PARAMETERS ---
            temperature=0.1,         # Minimize hallucination
            top_p=0.95,              # Nucleus sampling
            max_tokens=4096,         # Context window
            seed=1337,               # Attempt determinism

            # --- OPENROUTER CONTROL PLANE (The "Comprehensive" Block) ---
            extra_body={
                "provider": {
                    # 1. QUANTIZATION STRICTNESS
                    # Force 16-bit precision. Reject 4-bit/8-bit compressed models.
                    "quantizations": ["fp16", "bf16"],

                    # 2. PROVIDER PREFERENCE (Throughput + Quality)
                    # Prioritize providers known for raw model serving without hidden filters
                    "order": ["Google", "Vertex", "Together", "Fireworks", "Hyperbolic"],

                    # 3. FALLBACK POLICY
                    # False = Strict Science Mode (Fail if fp16 unavailable)
                    # True = Production Mode (Allow downgrade to int8 if necessary)
                    "allow_fallbacks": False,

                    # 4. DATA PRIVACY
                    # "deny" = Only route to providers that do not log inputs for training
                    "data_collection": "deny",

                    # 5. BLACKLIST
                    # Exclude providers known for high latency or aggressive rate limits
                    "ignore": ["DeepInfra"]
                },

                # 6. EXTENDED PARAMETERS (Model dependent)
                "top_k": 40,                 # Hard cap on token selection pool
                "repetition_penalty": 1.1,   # Slight penalty to prevent loops
                # "transforms": ["middle-out"], # Removed for raw native model outputs
                "models": FALLBACK_MODELS,   # Automatic failover list

                # 7. REASONING EFFORT (For o1/new Gemini models)
                "reasoning": { "effort": "high" }
            }
        )

        latency = time.time() - start_time

        # Extract Results
        content = completion.choices[0].message.content
        provider_info = extract_provider_metadata(completion)

        print(f"[{sample_id}] SUCCESS | Latency: {latency:.2f}s")
        print(f"[{sample_id}] Provider Info: {provider_info}")
        return content

    except RateLimitError:
        print(f"[{sample_id}] ERROR: 429 Rate Limit. Backing off...")
        return None
    except APIConnectionError as e:
        print(f"[{sample_id}] ERROR: Connection failed: {str(e)}")
        return None
    except Exception as e:
        print(f"[{sample_id}] CRITICAL: {str(e)}")
        return None

# ==========================================
# EXECUTION
# ==========================================
if __name__ == "__main__":
    # Validate Environment
    if not API_KEY:
        print("\n⚠️  WARNING: 'OPENROUTER_API_KEY' is not set.")
        print("   Set it via: export OPENROUTER_API_KEY='sk-or-...'\n")

    test_prompts = [
        "Return a JSON object containing the molar mass of Caffeine and Adenosine.",
        "Write a Python function for Merge Sort using type hints. Return JSON wrapper.",
    ]

    print(f"--- Starting High-Fidelity Batch on {PRIMARY_MODEL} ---")

    for i, prompt in enumerate(test_prompts):
        result = execute_high_fidelity_call(prompt, sample_id=f"SAMPLE_{i+1}")
        if result:
            print(f"> Result Preview: {result[:100]}...\n")
        time.sleep(2) # Respectful pacing

    print("--- Batch Complete ---")

# Validate Environment
if not API_KEY:
    print("\n⚠️  WARNING: 'OPENROUTER_API_KEY' is not set.")
    print("   Set it via: export OPENROUTER_API_KEY='sk-or-...' or Colab Secrets\n")

test_prompts = [
    "Return a JSON object containing the molar mass of Caffeine and Adenosine.",
    "Write a Python function for Merge Sort using type hints. Return JSON wrapper.",
]

print(f"--- Starting High-Fidelity Batch on {PRIMARY_MODEL} ---")

for i, prompt in enumerate(test_prompts):
    result = execute_high_fidelity_call(prompt, sample_id=f"SAMPLE_{i+1}")
    if result:
        print(f"> Result Preview: {result[:100]}...\n")
    time.sleep(2) # Respectful pacing

print("--- Batch Complete ---")

